//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCollection {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class AppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSettings defaultInstance = ((AppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSettings())));
        
        public static AppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=DESKTOP-F9849QL\\SQLEXPRESS;Database=AutoCollection;Trusted_connection=True" +
            ";Encrypt=False;TrustServerCertificate=False;")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
            set {
                this["ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"select nomdoc, idproxy, idtake
from (
	select t1.nomdoc, t1.id idproxy, isnull(t2.id,0) idtake 
	from actions t1 
	left join actions t2 on t2.idevt = 2 and t2.nomdoc = t1.nomdoc and t1.idauto = t2.idauto
	where t1.idauto = @pidauto and @pdt between t1.bdate and t1.edate and t1.idevt = 1
) tabp")]
        public string NotTakenProxy {
            get {
                return ((string)(this["NotTakenProxy"]));
            }
            set {
                this["NotTakenProxy"] = value;
            }
        }
    }
}
