//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallAccounting.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"select workername, deptname, deptlocation, phonenumber
,sum(calltime) sumtime, sum(calltime*calltime) allsum
from phonesview
where calldate between @pdbegin and @pdend and calltype = 'Исходящий'
group by workername, deptname, deptlocation, phonenumber
having sum(calltime*calltime) > @psum")]
        public string ReportCallsQuery {
            get {
                return ((string)(this["ReportCallsQuery"]));
            }
            set {
                this["ReportCallsQuery"] = value;
            }
        }
    }
}
